### ISSUE TITLE
Gamemode mismatch

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/MagicCobblestoneGenerator#29]
#### Describe the bug

MagicCobblestoneGenerator build 83 uses "SkyGrid" tiers instead of default tiers
_(I'm not sure which exact version of MagicCobblestoneGenerator causes this. It should be somewhere between 79 and 83)_
#### Steps to reproduce the behavior

I was updating my server from build 78 to 83. I noticed that the generator gave blocks I don't use.
1. test server with latest build 83 of the MagicCobblestoneGenerator addon.
2. made a cobble gen
3. started chopping
4. noticed dirt created
5. dirt is not in the default tiers. It is however part of the SkyGrid default tier
6. continued chopping. Got gold ore and coal ore.
#### Screenshots and videos

![2019-11-18_12 57 22](https://user-images.githubusercontent.com/28690790/69051426-938f2400-0a04-11ea-815d-84002d0de730.png)
![2019-11-18_13 09 49](https://user-images.githubusercontent.com/28690790/69051504-d6e99280-0a04-11ea-8b5b-ddb7cd743e98.png)

#### Expected behavior

Default tiers should be applied
#### Server

 - OS: **Linux**
 - Java version: **Openjdk 1.8.0_212**

#### Plugins

```
BentoBox, ChestShop, dynmap*, LuckPerms, mcMMO, PlaceholderAPI*, PlugMan, Vault, WorldBorder, WorldEdit, WorldGuard
```

##### BentoBox and Addons

```
Running PAPER 1.14.4.
BentoBox version: 1.9.0-SNAPSHOT-b1486
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.1-SNAPSHOT-b149 (ENABLED)
BSkyBlock 1.9.0-SNAPSHOT-b525 (ENABLED)
Challenges 0.9.0-SNAPSHOT-#393 (ENABLED)
Level 1.9.0-SNAPSHOT-b303 (ENABLED)
Limits 1.9.0-SNAPSHOT-b179 (ENABLED)
MagicCobblestoneGenerator 1.7.1-SNAPSHOT-#83 (ENABLED)
Warps 1.8.2-SNAPSHOT-b201 (ENABLED)
```

##### Configuration

 - Database: **JSON** 

### Additional context

Default tier:
```
tiers:
  default:
    min-level: 0
    name: "Stone Level"
    blocks:
      STONE: 10
      COBBLESTONE: 89
      GRAVEL: 1
```
Default SkyGrid tier:
```
gamemodes:
  SkyGrid:
    default:
      min-level: -1
      name: "Diamond Level"
      blocks:
        STONE: 10
        DIORITE: 1
        GRANITE: 1
        ANDESITE: 1
        COBBLESTONE: 89
        GRAVEL: 1
        COAL_ORE: 1
        IRON_ORE: 1
        GOLD_ORE: 1
        LAPIS_ORE: 1
        REDSTONE_ORE: 1
        DIRT: 1
        DIAMOND_ORE: 1
        EMERALD_ORE: 1
```
