### ISSUE TITLE
Allow color codes in generator description

### ISSUE THREAD

**Issue by Momonche** [BentoBoxWorld/MagicCobblestoneGenerator#63]
#### Is your feature request related to a problem?
I can't use color codes in generator description
```
tiers:
  # generator ID
  stone_age:
    # Display name for users
    name: "Générateur Cobblestone"
    # Description in lore message
    description:
      - "&aGénérateur Cobblestone"
      - "&6Stone"
      - "&6Cobblestone"
      - "&6Diorite"
      - "&6Andesite"
      - "&6Gravier"
```
![0rfuWUtJHgij](https://user-images.githubusercontent.com/37519498/87595191-72471a80-c6ee-11ea-8c80-9df1ded9c87a.png)

#### Describe the solution you'd like us to implement.
Possibility to use Minecraft color codes (and hexa ?)
